### ISSUE TITLE
Missing `Debug` impls on public types

### ISSUE THREAD

**Issue by EliasHolzmann** [siketyan/apdu-rs#17]
I noticed that apdu-rs does not implement `Debug` for all public types. After adding `#![warn(missing_debug_implementations)]` to all crates, the compiler tells me that they are missing for the following types:

- `apdu_core::Command`
- `apdu::command::ReadBinaryCommand`
- `apdu::command::SelectFileCommand`
- `apdu::command::VerifyCommand`

This makes debugging quite a bit harder than it needs to be. Is this by design, or simply an oversight? If the latter, would you welcome a pull request enabling the `missing_debug_implementations` warning and adding `Debug` impls for those types?

**Comment by siketyan** [comment]
@EliasHolzmann 
Hi, thank you for reporting this!
Yes, it is just an oversight. There were no design considerations here.
I am going to fix it in a few days, also pull request is welcome!

**Comment by siketyan** [comment]
@EliasHolzmann 
We have just released v0.4.0 which contains the fix based on your feedback.
Please be careful on upgrading about interface changes due to supporting no_std environments (#16), which is also contained in this release.

**Comment by EliasHolzmann** [comment]
Damn, you're fast. Thank you!
